/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import Panel.ClassePanel;
import Panel.ConfigPanel;
import Panel.ElevePanel;
import Panel.MatierePanel;
import Panel.NotePanel;
import Panel.PMCPanel;
import Panel.ProfesseurPanel;

/**
 *
 * @author ATH
 */
public class ConfigForm extends javax.swing.JFrame {

    /**
     * Creates new form ConfigForm
     */
    public ConfigForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelImage1 = new rojerusan.RSPanelImage();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        menu_item_eleve = new javax.swing.JMenuItem();
        menu_item_enseignant = new javax.swing.JMenuItem();
        jMenuItem_classe = new javax.swing.JMenuItem();
        menu_item_ue = new javax.swing.JMenuItem();
        jMenuItem_attribution_matiere = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menu_item_gestion_matiere = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuration");

        javax.swing.GroupLayout rSPanelImage1Layout = new javax.swing.GroupLayout(rSPanelImage1);
        rSPanelImage1.setLayout(rSPanelImage1Layout);
        rSPanelImage1Layout.setHorizontalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1110, Short.MAX_VALUE)
        );
        rSPanelImage1Layout.setVerticalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 656, Short.MAX_VALUE)
        );

        jMenu1.setText("Fichier");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edition");

        menu_item_eleve.setText("Elève");
        menu_item_eleve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_eleveActionPerformed(evt);
            }
        });
        jMenu2.add(menu_item_eleve);

        menu_item_enseignant.setText("Enseignant");
        menu_item_enseignant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_enseignantActionPerformed(evt);
            }
        });
        jMenu2.add(menu_item_enseignant);

        jMenuItem_classe.setText("Classe");
        jMenuItem_classe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_classeActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_classe);

        menu_item_ue.setText("Matière");
        menu_item_ue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_ueActionPerformed(evt);
            }
        });
        jMenu2.add(menu_item_ue);

        jMenuItem_attribution_matiere.setText("Attribution Matière");
        jMenuItem_attribution_matiere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_attribution_matiereActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_attribution_matiere);
        jMenu2.add(jSeparator1);

        menu_item_gestion_matiere.setText("Gestion des notes");
        menu_item_gestion_matiere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_gestion_matiereActionPerformed(evt);
            }
        });
        jMenu2.add(menu_item_gestion_matiere);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Programmation");

        jMenuItem1.setText("Paramètre");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("Matière");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Help");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menu_item_eleveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_eleveActionPerformed
        this.setContentPane(new ElevePanel());
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_menu_item_eleveActionPerformed

    private void menu_item_enseignantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_enseignantActionPerformed
        this.setContentPane(new ProfesseurPanel());
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_menu_item_enseignantActionPerformed

    private void menu_item_ueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_ueActionPerformed
        this.setContentPane(new MatierePanel());
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_menu_item_ueActionPerformed

    private void menu_item_gestion_matiereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_gestion_matiereActionPerformed
        //this.setContentPane(new CoursPan());
        this.setContentPane(new NotePanel());
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_menu_item_gestion_matiereActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.setContentPane(new ConfigPanel());
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem_classeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_classeActionPerformed
        this.setContentPane(new ClassePanel());
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_jMenuItem_classeActionPerformed

    private void jMenuItem_attribution_matiereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_attribution_matiereActionPerformed
        this.setContentPane(new PMCPanel());
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_jMenuItem_attribution_matiereActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.setContentPane(new MatierePanel());
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfigForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ConfigForm().setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem_attribution_matiere;
    private javax.swing.JMenuItem jMenuItem_classe;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem menu_item_eleve;
    private javax.swing.JMenuItem menu_item_enseignant;
    private javax.swing.JMenuItem menu_item_gestion_matiere;
    private javax.swing.JMenuItem menu_item_ue;
    private rojerusan.RSPanelImage rSPanelImage1;
    // End of variables declaration//GEN-END:variables

}
